title Hello World
echo Hello World
set a=0
title Error detected
color A
prompt VIRUS DETECTED
cls
color 09
start errormassagebasic.vbs
color 4C
start errormassagebasic.vbs
color 7F
start errormassagebasic.vbs
color 3B
start errormassagebasic.vbs
color 4E
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
start errormassagebasic.vbs
color 5B
color 3C
color 19
color C
color B
color C
prompt WARNING
color D
color E
color F
color AE
color FC
color AC
color CA
prompt WARNING WARNING WARNING WARNING WARNING
color 09
color 4C
color 7F
color 3B
color 4E
color 5B
color 3C
color 19
color C
prompt VIRUS DETECTE ATTENTION VIRUS DETECTE ATTENTION
color B
color C
color D
color E
color F
color AE
color FC
color AC
color CA
prompt VOUS ETES UN IDIOT !!!
color 09
prompt VOUS ETES UN IDIOT !!!!!!
color 4C
prompt VOUS ETES UN IDIOT !!!!!!!!!
color 7F
prompt VOUS ETES UN IDIOT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
color 3B
prompt VOUS ETES UN IDIOT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
color 4E
color 5B
color 3C
color 19
color C
color B
color C
color D
prompt VIRUS DETECTE ATTENTION VIRUS DETECTE ATTENTION
color E
color F
color AE
color FC
color AC
color CA
color 09
color 4C
color 7F
color 3B
color 4E
prompt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
color 5B
color 3C
color 19
color C
color B
color C
color D
color E
color F
color AE
color FC
prompt WARNING WARNING WARNING WARNING WARNING
color AC
color CA
color 09
color 4C
color 7F
color 3B
color 4E
color 5B
color 3C
color 19
color C
color B
color C
color D
color E
color F
prompt Attentio!!n!Warni!!!!ngAtte!!!!!!!ntionWarn!ingAtten!!!!tionW!arning!!!!!!!!!!!!!!!
color AE
color FC
color AC
color CA
color 09
color 4C
color 7F
color 3B
color 4E
prompt VOTRE ORDINATEUR A ETE PIRATE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
color 5B
color 3C
color 19
color C
color B
color C
color D
color E
color F
color AE
color FC
color AC
color CA
start errormassage.vbs
cls
